application:
  lang: pt-br
  title: Sloth
  subtitle: Take your time!
  icon: /static/images/logo.png
  logo: /static/images/logo.png
  version: 0.0.1
  oauth:
    govbr:
      name: gov.br
      client_id: $GOVBR_CLIENTE_ID
      client_secret: $GOVBR_CLIENT_SECRET
      redirect_uri: /app/login/govbr/
      authorize_url: $GOVBR_AUTHORIZE_URL
      access_token_url: $GOVBR_ACCESS_TOKEN_URL
      user_data_url: $GOVBR_USER_DATA_URL
      user_logout_url: $GOVBR_LOGOUT_URL
      user_scope:
      user_data:
        create: false
        username: sub
        email: email
  groups:
    administrador: Administrador
    operador: Operador
  index: dashboard
  dashboard:
    actions:
    toolbar:
    top:
    center:
    boxes:
    search:
    usermenu:
      - dev.icons
      - user.users
      - log.logs
      - deletion.deletions
      - auth.logout
    adder:
    tools:
    settings:
  menu:
    users:Item 1:
      Item 1.1:
        Sair: logout
    Sair: auth.logout
  theme:
    colors:
      primary: "#1351b4"
      secondary: "#071e41"
      auxiliary: "#2670e8"
      highlight: "#0c326f"
      info: "#1351b4"
      success: "#1351b4"
      warning: "#fff5c2"
      danger: "#e52207"
    border:
      radius: 100em"
    background:
      info: "#d4e5ff"
